/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace LoreKeeper {
  export type StoryEntryStruct = {
    contributor: AddressLike;
    sentence: string;
    timestamp: BigNumberish;
    index: BigNumberish;
  };

  export type StoryEntryStructOutput = [
    contributor: string,
    sentence: string,
    timestamp: bigint,
    index: bigint
  ] & {
    contributor: string;
    sentence: string;
    timestamp: bigint;
    index: bigint;
  };
}

export interface LoreKeeperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSentence"
      | "entries"
      | "getAllEntries"
      | "getEntry"
      | "getEntryCount"
      | "owner"
      | "resetStory"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SentenceAdded"): EventFragment;

  encodeFunctionData(functionFragment: "addSentence", values: [string]): string;
  encodeFunctionData(
    functionFragment: "entries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEntries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resetStory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSentence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetStory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace SentenceAddedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    sentence: string,
    index: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    sentence: string,
    index: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    contributor: string;
    sentence: string;
    index: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LoreKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): LoreKeeper;
  waitForDeployment(): Promise<this>;

  interface: LoreKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSentence: TypedContractMethod<[sentence: string], [void], "nonpayable">;

  entries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        contributor: string;
        sentence: string;
        timestamp: bigint;
        index: bigint;
      }
    ],
    "view"
  >;

  getAllEntries: TypedContractMethod<
    [],
    [LoreKeeper.StoryEntryStructOutput[]],
    "view"
  >;

  getEntry: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        contributor: string;
        sentence: string;
        timestamp: bigint;
        entryIndex: bigint;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  resetStory: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSentence"
  ): TypedContractMethod<[sentence: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        contributor: string;
        sentence: string;
        timestamp: bigint;
        index: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllEntries"
  ): TypedContractMethod<[], [LoreKeeper.StoryEntryStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        contributor: string;
        sentence: string;
        timestamp: bigint;
        entryIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "resetStory"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "SentenceAdded"
  ): TypedContractEvent<
    SentenceAddedEvent.InputTuple,
    SentenceAddedEvent.OutputTuple,
    SentenceAddedEvent.OutputObject
  >;

  filters: {
    "SentenceAdded(address,string,uint256,uint256)": TypedContractEvent<
      SentenceAddedEvent.InputTuple,
      SentenceAddedEvent.OutputTuple,
      SentenceAddedEvent.OutputObject
    >;
    SentenceAdded: TypedContractEvent<
      SentenceAddedEvent.InputTuple,
      SentenceAddedEvent.OutputTuple,
      SentenceAddedEvent.OutputObject
    >;
  };
}
